### PR TITLE
turn ip.ip into ip so the examples actually work

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by thimslugga** [comment]
The examples in the tutorial do work and the changes you made actually breaks them. They are two different objects,

In [4]: from netaddr import *
In [5]: ip = IPNetwork('fe80::dead:beef/64')

In [20]: ip.bits()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-7227c9a78dd2> in <module>()
----> 1 ip.bits()

AttributeError: 'IPNetwork' object has no attribute 'bits'

In [19]: ip.ip.bits()
Out[19]: '1111111010000000:0000000000000000:0000000000000000:0000000000000000:0000000000000000:0000000000000000:1101111010101101:1011111011101111'

In [7]: ip
Out[7]: IPNetwork('fe80::dead:beef/64')

In [9]: ip.ip
Out[9]: IPAddress('fe80::dead:beef')

In [14]: type(ip)
Out[14]: netaddr.ip.IPNetwork

In [15]: type(ip.ip)
Out[15]: netaddr.ip.IPAddress

**Comment by Habbie** [comment]
Ok, I see it and of course you are right. How about renaming the `IPNetwork` example variables to `net`?

**Comment by drkjam** [comment]
Nothing to do here so closing this.

**Comment by Habbie** [comment]
I guess that's a no then.

**Pull request closed without merging**
